### PR TITLE
Allow adding additional volumes

### PR DESCRIPTION
**Pull request by puzzleitc**
Allows to add additional volumes to the cloudscale.ch vm.

Example:

`docker-machine create --driver cloudscale --cloudscale-image ubuntu-18.04 --cloudscale-ssh-user ubuntu --cloudscale-flavor flex-2 --cloudscale-volumes "{\"name\": \"morestorage\", \"type\": \"ssd\", \"size_gb\": 1}" spl-test`

### CODE REVIEW

**Comment by puzzleitc** [comment]
not sure if this is the best golang code ;)
I wanna use it to extend the ui-driver-cloudscale for rancher. What do you think? Open for suggestions ;)

**Comment by splattner** [comment]
oh, I was logged in as puzzle, pr comes from me ;)

**Comment by davidhalter** [comment]
Hi @splattner 

Thanks for your contribution!

We created a ticket for this. We hope to look at this once we have more time.

**Comment by alakae** [comment]
Hi @splattner 

Thank you for your contribution.

* Please note that it's currently not possible to specify the name of non-root volumes when they are created together with a server. See [Create a Server](https://www.cloudscale.ch/en/api/v1#servers-create):
  > volumes: A list of volume objects specifying the volumes to be attached to the new server. A volume object has the attributes size_gb and type. Default is [].
* What is your opinion on introducing two separate options `--cloudscale-volume-ssd N` and `--cloudscale-volume-bulk N`? I think it makes the driver easier to use as a CLI tool. 

I am happy to implement the changes. Please let me know.

**Comment by alakae** [comment]
Additionally, we should check if it's possible to delete attached volumes together with a server when running `docker-machine rm`.

**Comment by splattner** [comment]
>     * What is your opinion on introducing two separate options `--cloudscale-volume-ssd N` and `--cloudscale-volume-bulk N`? I think it makes the driver easier to use as a CLI tool.

I'm also fine with that!

> I am happy to implement the changes. Please let me know.

That would be great! thx

**Pull request merged**
